### ISSUE TITLE
Either TypeError or Unexpected Token while trying to run the repl

### ISSUE THREAD

**Issue by mhash17** [HerringtonDarkholme/typescript-repl#13]
hi, i'm always getting the following error (@ win7 cmd):

```
TSUN : TypeScript Upgraded Node
type in TypeScript expression to evaluate
type :help for commands in repl

> function myfunc() {return 343434}
SyntaxError: Unexpected token :
    at Object.exports.runInContext (vm.js:43:16)
    at startEvaluate (C:\...\npm\node_modules\tsun\bin\src\repl.js:199:25)
    at replLoop (C:\...\npm\node_modules\tsun\bin\src\repl.js:223:9)
    at C:\...\npm\node_modules\tsun\bin\src\repl.js:330:9
    at Interface._onLine (readline.js:210:5)
    at Interface._line (readline.js:551:8)
    at Interface._ttyWrite (readline.js:828:14)
    at ReadStream.onkeypress (readline.js:107:10)
    at emitTwo (events.js:87:13)
    at ReadStream.emit (events.js:172:7)
```

and when i try to run it with cygwin the repl is not even starting with following error:

```
$ tsun
TSUN : TypeScript Upgraded Node
type in TypeScript expression to evaluate
type :help for commands in repl

> readline.js:617
  var strBeforeCursor = this._prompt + this.line.substring(0, this.cursor);
                                                ^
TypeError: Cannot read property 'substring' of undefined
    at Interface._getCursorPos (readline.js:617:49)
    at afterSuggestion (C:\...\npm\node_modules\tsun\node_modules\node-color-readline\index.js:75:26)
    at renderCurrentLine (C:\...\npm\node_modules\tsun\node_modules\node-color-readline\index.js:71:5)
    at Interface._writeToOutput (C:\...\npm\node_modules\tsun\node_modules\node-color-readline\index.js:42:5)
    at Interface.prompt (readline.js:186:10)
    at Interface.question (readline.js:199:12)
    at repl (C:\Users\b.haschmi\AppData\Roaming\npm\node_modules\tsun\bin\src\repl.js:289:8)
    at Object.startRepl (C:\...\npm\node_modules\tsun\bin\src\repl.js:335:5)
    at Object.<anonymous> (C:\...\npm\node_modules\tsun\bin\tsun.js:31:8)
    at Module._compile (module.js:409:26)
```

**Comment by HerringtonDarkholme** [comment]
Sorry, I cannot reproduce it on my Windows virtual machine.

Please add a minimal reproducible example in this issue. Probably, you have fired up `tsun` in a wrong directory or so.

**Comment by mhash17** [comment]
Ok, tried it again with a new clear installation and just only using the win7 cmd - and it worked fine. Sorry for that. So complications only exist when using cygwin (maybe caused by data conversion/wrapping ..).
