### ISSUE TITLE
Error while excuting `tsun`

### ISSUE THREAD

**Issue by amio** [HerringtonDarkholme/typescript-repl#2]
```
/usr/local/lib/node_modules/tsun/bin/tsun.js:214
arations[file] = service.getSourceFile(file).getNamedDeclarations().map(functi
                                                                    ^
TypeError: undefined is not a function
    at /usr/local/lib/node_modules/tsun/bin/tsun.js:214:81
    at Object.<anonymous> (/usr/local/lib/node_modules/tsun/bin/tsun.js:223:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/tsun/bin/tsun:2:1)
    at Module._compile (module.js:460:26)
```

**Comment by HerringtonDarkholme** [comment]
Oh... This is an incompatible TypeScript upgrade. `getNamedDeclarations` is no longer a public method on `SourceFile`. I will try to fix it.

**Comment by HerringtonDarkholme** [comment]
I can use private api to extract identifiers, in order to support `:type`, `:detail`  and other commands.
But this is hazardous. I cannot guarantee these commands in next release.

**Comment by HerringtonDarkholme** [comment]
Fixed in https://github.com/HerringtonDarkholme/typescript-repl/commit/c2e62a37b33a25141e2d84394cbc42e2ed490302

**Comment by amio** [comment]
"Who would like some pervert like you, baka!"

**Comment by HerringtonDarkholme** [comment]
( ´◔ ‸◔`)﻿ oh... that's totally not moe spoken by a guy
