### ISSUE TITLE
No such file @types/node

### ISSUE THREAD

**Issue by arichiardi** [HerringtonDarkholme/typescript-repl#33]
Hello folks! Thanks for this wonderful REPL!

I am trying it out locally and I got it working but I initially was getting:

```
Error: ENOENT: no such file or directory, open '/home/arichiardi/.config/yarn/global/node_modules/tsun/node_modules/@types/node/index.d.ts'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at /home/arichiardi/.config/yarn/global/node_modules/tsun/bin/src/service.js:96:25
    at Object.<anonymous> (/home/arichiardi/.config/yarn/global/node_modules/tsun/bin/src/service.js:106:3)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
```

That made me realize I had to do run the following too:

```
yarn global add typescript
yarn global add @types/node
yarn global add tsun
```

It seems that with `yarn` those where not dragged in as transitive deps.

**Comment by andersonba** [comment]
ping

**Comment by rafpaf** [comment]
I ran into the same problem after installing tsun with `pnpm install -g tsun`. As a workaround, I did:

```
cd ~/.local/share/pnpm/global/5/.pnpm/tsun@0.5.1_typescript@4.7.4/node_modules/tsun/node_modules
ln -s ../../@types .
```
