### ISSUE TITLE
Could not find file on starting tsun

### ISSUE THREAD

**Issue by burgerga** [HerringtonDarkholme/typescript-repl#4]
I installed using `npm install -g tsun` with output 

```
/usr/bin/tsun -> /usr/lib/node_modules/tsun/bin/tsun
tsun@0.0.9 /usr/lib/node_modules/tsun
├── colors@1.1.2
├── temp@0.8.3 (os-tmpdir@1.0.1, rimraf@2.2.8)
├── typescript@1.6.0-dev.20150803
└── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
```

but when I try to run it I get the following message:

```
/usr/lib/node_modules/tsun/node_modules/typescript/lib/typescript.js:41694
                throw new Error("Could not find file: '" + fileName + "'.");
                      ^
Error: Could not find file: '/usr/lib/node_modules/tsun/node_modules/typescript/bin/lib.core.es6.d.ts'.
   at SyntaxTreeCache.getCurrentSourceFile    (/usr/lib/node_modules/tsun/node_modules/typescript/lib/typescript.js:41694:23)
   at Object.getSourceFile (/usr/lib/node_modules/tsun/node_modules/typescript/lib/typescript.js:45521:36)
   at /usr/lib/node_modules/tsun/bin/tsun.js:228:57
   at Object.<anonymous> (/usr/lib/node_modules/tsun/bin/tsun.js:237:3)
   at Module._compile (module.js:460:26)
   at Object.Module._extensions..js (module.js:478:10)
   at Module.load (module.js:355:32)
   at Function.Module._load (module.js:310:12)
   at Module.require (module.js:365:17)
   at require (module.js:384:17)
```

**Comment by HerringtonDarkholme** [comment]
Thanks for your reporting!
TS team changed their directory so I will update TSUN soon

**Comment by HerringtonDarkholme** [comment]
closed via https://github.com/HerringtonDarkholme/typescript-repl/commit/81d6be6735580b961c31bd29c0fecf448fc6fec0
