### ISSUE TITLE
Import statements fail

### ISSUE THREAD

**Issue by dchacke** [HerringtonDarkholme/typescript-repl#7]
First, I run `tsun`, then I load a module:

``` typescript
> import { Component } from 'angular2/core'
```

Expecting `Component` to be defined, I attempt to use it:

``` typescript
> Component
ReferenceError: Component is not defined
    at evalmachine.<anonymous>:2:1
    at Object.exports.runInContext (vm.js:44:17)
    at startEvaluate (/Users/dch/.nvm/versions/node/v4.0.0/lib/node_modules/tsun/bin/tsun.js:372:25)
    at replLoop (/Users/dch/.nvm/versions/node/v4.0.0/lib/node_modules/tsun/bin/tsun.js:400:9)
    at /Users/dch/.nvm/versions/node/v4.0.0/lib/node_modules/tsun/bin/tsun.js:469:9
    at Interface._onLine (readline.js:208:5)
    at Interface._line (readline.js:546:8)
    at Interface._ttyWrite (readline.js:823:14)
    at ReadStream.onkeypress (readline.js:105:10)
    at emitTwo (events.js:87:13)
```

This happens to me when trying to import npm modules as well as files I wrote myself, so it doesn't seem to be related to any specific module I'm loading.

npm version: 2.14.2
node version: v4.0.0
tsun version: 0.0.13

**Comment by HerringtonDarkholme** [comment]
You have to place `angular.d.ts` under the typing directory. Currently tsun does not have a decent definition resolution strategy. https://github.com/HerringtonDarkholme/typescript-repl/blob/master/tsun.ts#L115

If you are playing with angular2, plunkr is a better choice though

**Comment by dchacke** [comment]
This is not related to Angular. I can't even load a class from a file in the same directory:

foo.ts:

``` typescript
export class Foo {
}
```

tsun:

``` typescript
> import {Foo} from './foo'
'use strict'
> Foo
ReferenceError: Foo is not defined
    at evalmachine.<anonymous>:2:1
    at Object.exports.runInContext (vm.js:44:17)
    at startEvaluate (/Users/dch/.nvm/versions/node/v4.0.0/lib/node_modules/tsun/bin/tsun.js:372:25)
    at replLoop (/Users/dch/.nvm/versions/node/v4.0.0/lib/node_modules/tsun/bin/tsun.js:400:9)
    at /Users/dch/.nvm/versions/node/v4.0.0/lib/node_modules/tsun/bin/tsun.js:469:9
    at Interface._onLine (readline.js:208:5)
    at Interface._line (readline.js:546:8)
    at Interface._ttyWrite (readline.js:823:14)
    at ReadStream.onkeypress (readline.js:105:10)
    at emitTwo (events.js:87:13)
```

**Comment by HerringtonDarkholme** [comment]
It seems typescript mistakenly transpile `import {Foo} from './foo'`, if you change it to `import Foo = require('./foo')`. It works.

**Comment by dchacke** [comment]
Nope:

``` typescript
> import Foo = require('./foo')
'use strict'
> Foo
ReferenceError: Foo is not defined
    at evalmachine.<anonymous>:2:1
    at Object.exports.runInContext (vm.js:44:17)
    at startEvaluate (/Users/dch/.nvm/versions/node/v4.0.0/lib/node_modules/tsun/bin/tsun.js:372:25)
    at replLoop (/Users/dch/.nvm/versions/node/v4.0.0/lib/node_modules/tsun/bin/tsun.js:400:9)
    at /Users/dch/.nvm/versions/node/v4.0.0/lib/node_modules/tsun/bin/tsun.js:469:9
    at Interface._onLine (readline.js:208:5)
    at Interface._line (readline.js:546:8)
    at Interface._ttyWrite (readline.js:823:14)
    at ReadStream.onkeypress (readline.js:105:10)
    at emitTwo (events.js:87:13)
```

**Comment by HerringtonDarkholme** [comment]
This is partially fixed in https://github.com/HerringtonDarkholme/typescript-repl/commit/e856b05c72c2156f5d4b1129bc6abe577c6fbdda.

But importing ts file is still under working

**Comment by HerringtonDarkholme** [comment]
Fixed in https://github.com/HerringtonDarkholme/typescript-repl/commit/bf7dd07b43704e9ffa7fe325c4e3cbba2975e9cf
